### ISSUE TITLE
Take binaries out of the repository.

### ISSUE THREAD

**Issue by alyssarosenzweig** [GoEverywhere/Go-Everywhere#51]
They're annoying and slow down `git clone` on platforms that don't need them. (Although, you'll need to be clever about exactly _how_ you remove them; a simple `git rm` won't be enough as they will remain in history. See https://help.github.com/articles/remove-sensitive-data/ for details. :smile: )

**Comment by bleush38p** [comment]
(Not sure if this is already implied, but) `node_modules` should be removed too. Add any dependencies to the manifest instead (I'd just include nm and a build folder in `.gitignore`.

**Comment by bobbybee** [comment]
@bleush38p Agreed.
